#!/usr/bin/env python3
"""Emit the plugin.yml suite: block as docs/suite.json.

The shared session player (chris-peterson.github.io/claude-marketplace/session-player.js)
fetches it to hydrate the .cw-session mount points on the docs pages — the same
source the marketplace SPA reads, so the hub and the docs live preview never
drift. docs/suite.json is a render target (gitignored); regenerated by
`just docs` and the Pages deploy.
"""
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "plugin.yml"
TARGET = ROOT / "docs" / "suite.json"


def main() -> int:
    spec = yaml.safe_load(SOURCE.read_text()) or {}
    suite = spec.get("suite")
    if not suite:
        sys.stderr.write("plugin.yml has no suite: block — the docs session preview needs it\n")
        return 1
    TARGET.write_text(json.dumps(suite, indent=2, ensure_ascii=False) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
